name: Post-Release Actions

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  post-release-actions:
    runs-on: ubuntu-latest
    # Only run if the PR was merged and it's a release PR
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'release/')
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT_TOKEN }}

      - name: Extract version from branch name
        id: version
        run: |
          BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          VERSION=${BRANCH_NAME#release/}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: Release ${{ steps.version.outputs.version }}
          body: |
            ## Release ${{ steps.version.outputs.version }}
            
            This release was automatically created after merging the release pull request.
            
            ### What's Changed
            See [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md) for detailed changes.
            
            ### Docker Images
            - `ghcr.io/${{ github.repository_owner }}/haos-addon-wnsm-sync:latest`
            - `ghcr.io/${{ github.repository_owner }}/haos-addon-wnsm-sync:${{ steps.version.outputs.version }}`
          draft: false
          prerelease: false

      - name: Notify completion
        run: |
          echo "🎉 Release ${{ steps.version.outputs.version }} completed successfully!"
          echo "📦 Docker images have been published"
          echo "📋 GitHub release has been created"
          echo "🔄 Your local repository is now ready to be synced with 'git pull'"
